# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.1
      HUGO_ENV: production
      HUGO_ENVIRONMENT: production
      HUGO_BUILD_DEST: public
      HUGO_BUILD_ARTIFACT: site.tar
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --destination ${{ runner.temp }}/${{ env.HUGO_BUILD_DEST }}

      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$RUNNER_TEMP/$HUGO_BUILD_DEST" \
            -cvf "$RUNNER_TEMP/$HUGO_BUILD_ARTIFACT" \
            --exclude=.git \
            --exclude=.github \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          retention-days: 1
          path: ${{ runner.temp }}/${{ env.HUGO_BUILD_ARTIFACT}}
          if-no-files-found: error

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
